main: com.cavetale.pictionary.PictionaryPlugin

name: Pictionary
version: 0.1
description: Pictionary Plugin
api-version: '1.20'

author: StarTux
website: https://github.com/StarTux/Pictionary

depend: [Core, Mytems, Chat, Fam, AFK]
softdepend: []

commands:

  cavepaintadmin:
    aliases: [cavepaintadm]
    description: Admin Command
    permission: cavepaint.admin
    usage: |-
      /pictionary

  cavepaint:
    aliases: []
    description: User Command
    permission: 

permissions:

  cavepaint.admin:
    description: Use /pictionary
    default: op

  cavepaint.player:
    description: Use /cavepaint
    default: op
